### PR TITLE
Fix Azure SDK target mapping

### LINKED ISSUE #2699: Key Vault not displayed on Azure Container Apps / AppInsight Application Map
### Expected behavior
I deploy several Java Spring Boot micro services to ACA, I successfully see the AppInsight Application Map including Azure DB MySQL, all micro services, the Config-Server and 1 external akamai site but NOT Key Vault.

### Actual behavior
Key Vault should be displayed on the Map as each micro service back-end (not the API gateway) read a password secret from KV to connect to the DB.

### To Reproduce
[https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv)

#### Sample Application
If applicable, provide a sample application which reproduces the issue:
[https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv)

### System information
Please provide the following information:
 - SDK Version: ApplicationInsights-Java agent 3.4.1
 - OS type and version: mcr.microsoft.com/openjdk/jdk:11-mariner 
 - Application Server type and version (if applicable): N/A
 - Using spring-boot? **YES**
 - Additional relevant libraries (with version, if applicable):

See the POM at [https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/pom.xml](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/pom.xml) : 

```sh
    <!-- tip to verify the dependencies: mvn dependency:tree -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.13</version> <!-- /!\ Bug in Netty with Spring Boot 2.6.6, see https://github.com/netty/netty/issues/12343 -->
    </parent>

        <spring-cloud.version>2021.0.4</spring-cloud.version>
        <spring-cloud-azure.version>4.4.0</spring-cloud-azure.version>
        <spring-boot.version>2.6.13</spring-boot.version> <!-- /!\ Bug in Netty with Spring Boot 2.6.6, see https://github.com/netty/netty/issues/12343 -->

        <java.version>11</java.version>
        <maven.compiler.release>11</maven.compiler.release>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
```

Dockerfile example at [https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/docker/petclinic-customers-service/Dockerfile](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/docker/petclinic-customers-service/Dockerfile)

see also Bicep overiding the Docker command at [https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/iac/bicep/modules/aca/apps/aca-svc.bicep#189](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/iac/bicep/modules/aca/apps/aca-svc.bicep#189)

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

Kusto Query:

ContainerAppConsoleLogs_CL
| where Log_s contains "Application Insights"
| project c, AppName=ContainerAppName_s ,Revision=RevisionName_s, Message=Log_s
| sort by Time desc

```bash
LOG_ANALYTICS_WORKSPACE_CLIENT_ID=`az monitor log-analytics workspace show -n $LOG_ANALYTICS_WORKSPACE -g $RESOURCE_GROUP --query customerId  --out tsv`

az monitor log-analytics query \
  --workspace $LOG_ANALYTICS_WORKSPACE_CLIENT_ID \
  --analytics-query "ContainerAppConsoleLogs_CL | where Log_s contains 'Application Insights'  | where TimeGenerated > ago(4h) |  \
project Time =TimeGenerated, ContainerAppName_s,  Revision=RevisionName_s,  Log_s | sort by Time desc " \
  --out table > aca-petcliaca-appinsights.log
```

[aca-petcliaca-appinsights.log](https://github.com/microsoft/ApplicationInsights-Java/files/10006984/aca-petcliaca-appinsights.log)

### Screenshots
N/A

See also [https://github.com/microsoft/azure-container-apps/issues/290](https://github.com/microsoft/azure-container-apps/issues/290)

Note: this issue does NOT happen with Azure Spring Apps / AppInsight Application Map
See my project at [https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv](https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv)

### PR DESCRIPTION
**Pull request by trask**
See #2699

### CODE REVIEW

File: agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParser.java [hunk 1]
```diff
@@ -1,107 +1,212 @@
...
 import reactor.util.annotation.Nullable;
 
 public class UrlParser {
 
-  /**
-   * Returns the "target" (host:port) portion of the url.
-   *
-   * <p>Returns {@code null} if the target cannot be extracted from url for any reason.
-   */
+  // TODO remove this unused?
```
Comment (jeanbisutti) [inline agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParser.java:16]: 👍

File: agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserPathTest.java [hunk 2]
```diff
@@ -11,130 +11,80 @@ public class UrlParserPathTest {
 
   @Test
   public void testGetPathFromUrl() {
```
Comment (jeanbisutti) [inline agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserPathTest.java:13]: url could be null or empty? If yes, it would be valuable to add tests for these cases.

File: agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserTargetTest.java [hunk 3]
```diff
@@ -13,145 +13,209 @@ public class UrlParserTargetTest {
 
   @Test
```
Comment (jeanbisutti) [inline agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserTargetTest.java:14]: url could be null or empty? If yes, it would be valuable to add tests for these cases.

**Review by jeanbisutti — COMMENTED** [review]
I wonder whether all the `substring` calls are reasonable in terms of performance.

File: agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserPathTest.java (hunk 2 above)
Comment (trask) [reply agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserPathTest.java:13]: I added tests for empty and malformed. this method shouldn't be called with null url.

File: agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserTargetTest.java (hunk 3 above)
Comment (trask) [reply agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserTargetTest.java:14]: I added tests for empty and malformed. this method shouldn't be called with null url.

File: agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParser.java (hunk 1 above)
Comment (trask) [reply agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParser.java]: done

**Review by jeanbisutti — APPROVED** [review]
