### PR TITLE
Fix GCPerformanceCounter not working

### LINKED ISSUE #929: It's not possible to turn on GCPerformanceCounter using <JvmPC name="GC" enabled="true" />
It's not possible to turn on GCPerformanceCounter with such configuration:

```
 <PerformanceCounters collectionFrequencyInSec="60">
        <UseBuiltIn>true</UseBuiltIn>
        <Jvm enabled="true">
            <JvmPC name="GC" enabled="true" />
        </Jvm>
    </PerformanceCounters>
```

Is it possible to turn it on somehow?

### PR DESCRIPTION
**Pull request by trask**
Fix #929

### CODE REVIEW

File: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/GCPerformanceCounter.java [hunk 1]
```diff
@@ -80,7 +80,7 @@ public void report(TelemetryClient telemetryClient) {
             MetricTelemetry mtTotalTime = new MetricTelemetry(GC_TOTAL_TIME, timeToReport);
 
             mtTotalCount.markAsCustomPerfCounter();
-            mtTotalCount.markAsCustomPerfCounter();
+            mtTotalTime.markAsCustomPerfCounter();
```
Comment (littleaj) [inline core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/GCPerformanceCounter.java]: :) good catch

**Comment by littleaj** [comment]
@trask, is this going in beta3 or later?
