### PR TITLE
Fixed cast error in CpuPerformanceCounterCalculator constructor 

### LINKED ISSUE #432: NoClassDefFoundError: com/sun/management/OperatingSystemMXBean - WildFly 10/Java 8
Found on Windows running WildFly 10 with Java 1.8.0_144:

```
AI: ERROR 21-09-2017 17:28, 238: Failed to create ProcessCpuPerformanceCounter: com/sun/management/OperatingSystemMXBean
java.lang.NoClassDefFoundError: com/sun/management/OperatingSystemMXBean
 at com.microsoft.applicationinsights.internal.perfcounter.CpuPerformanceCounterCalculator.<init>(CpuPerformanceCounterCalculator.java:42)
 at com.microsoft.applicationinsights.internal.perfcounter.ProcessCpuPerformanceCounter.<init>(ProcessCpuPerformanceCounter.java:41)
 at com.microsoft.applicationinsights.internal.perfcounter.ProcessBuiltInPerformanceCountersFactory.getMutualPerformanceCounters(ProcessBuiltInPerformanceCountersFactory.java:71)
 at com.microsoft.applicationinsights.internal.perfcounter.ProcessBuiltInPerformanceCountersFactory.getWindowsPerformanceCounters(ProcessBuiltInPerformanceCountersFactory.java:94)
 at com.microsoft.applicationinsights.internal.perfcounter.ProcessBuiltInPerformanceCountersFactory.getPerformanceCounters(ProcessBuiltInPerformanceCountersFactory.java:50)
 at com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.initialize(AbstractPerformanceCounterModule.java:48)
 at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initializeComponents(TelemetryConfigurationFactory.java:484)
 at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initialize(TelemetryConfigurationFactory.java:111)
 at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:74)
 at com.microsoft.applicationinsights.TelemetryClient.<init>(TelemetryClient.java:81)
 at com.microsoft.applicationinsights.internal.agent.CoreAgentNotificationsHandler.<init>(CoreAgentNotificationsHandler.java:89)
 at com.microsoft.applicationinsights.internal.agent.AgentConnector.register(AgentConnector.java:78)
 at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.registerWebApp(WebRequestTrackingFilter.java:238)
 at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.initialize(WebRequestTrackingFilter.java:224)
 at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.init(WebRequestTrackingFilter.java:125)
 at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
 at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:84)
 at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:97)
 at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
 at io.undertow.servlet.core.ManagedFilter.getFilter(ManagedFilter.java:66)
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
 at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
 at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
 at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
 at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
 at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
 at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
 at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
 at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
 at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
 at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
 at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
 at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
 at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
 at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
 at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
```

The exception comes from _CpuPerformanceCounterCalculator_ which is attempting to use the _com.sun.management.OperatingSystemMXBean_ versus _java.lang.management.OperatingSystemMXBean_. It appears the com.sun.management.OperatingSystemMXBean is used for _getProcessCpuTime_ which is not available in the java.lang.* implementation.

### PR DESCRIPTION
**Pull request by littleaj**
Corrected issue where the constructor was expecting the `com.sun.management` implementation of the OperatingSystemMXBean.

Since there isn't a getter for ProcessCpuTime in the OperatingSystemMXBean interface, I opted to lookup the metric in the MBeanServer.

Fix #432

### CODE REVIEW

File: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/CpuPerformanceCounterCalculator.java [hunk 1]
```diff
@@ -68,4 +71,10 @@ public double getProcessCpuUsage() {
 
         return processCpuUsage;
     }
+
+    private long getProcessCpuTime() throws Exception {
```
Comment (dhaval24) [inline core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/CpuPerformanceCounterCalculator.java]: what is the performance impact of this lookup? Does this change of behavior add more CPU utilization. Upon looking the description of this method it seems like it creates a static object once and then keeps it in the memory so on all subsequent calls it pulls up the same object. https://docs.oracle.com/javase/8/docs/api/java/lang/management/ManagementFactory.html#getPlatformMXBean-java.lang.Class-
Can we instead of calling getPlatformMBeanServer() everytime do it once in the static block/constructor and store it as instance variable in the class. It will save the compiler time of calling the method.

**Comment by littleaj** [comment]
@dhaval24 The build failed due to an unrelated infrastructure issue. I triggered another one manually and it passed. There doesn't seem to be a way to retrigger the checks here, so I may have to make a change to the branch to trigger the checks again.

**Comment by dhaval24** [comment]
@littleaj Thanks for clarification on build.

**Comment by dan-crough-bmi** [comment]
I took a shot at this based on the above code and comments, and I no longer receive the previous error. See https://github.com/dan-crough-bmi/ApplicationInsights-Java/commit/72840a36a5ffeb1e644a724246dd04c54934dd50 . The change to DockerContextInitializer.java was simply to remove ambiguity for the Constants class to be used (Eclipse picked up wrong class). I can submit pull request if desired, or feel free to copy/paste code into this branch to push forward.

File: core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/CpuPerformanceCounterCalculator.java (hunk 1 above)
Comment (littleaj) [reply core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/CpuPerformanceCounterCalculator.java]: I ran some basic tests and the performance looks to be the same as before this change.

I like how @dan-crough-bmi refactored this and I'm going to integrate their changes. Thanks for contributing, @dan-crough-bmi !

**Comment by dhaval24** [comment]
@dan-crough-bmi @littleaj please have a look at comments I left on @dan-crough-bmi changes. I think our SDK's should not throw exceptions. It would be advisable to catch it. Please make changes accordingly before merging.

**Comment by dan-crough-bmi** [comment]
@dhaval24 Your suggested solution sounds good -- catch and log instead of throwing in constructor (getProcessCpu() exception is caught in getProcessCpuUsage() method -- assume that existing structure is acceptable). Provisions need to be made in getProcessCpuUsage() for "partially constructed" class in the event of only-logged exception in constructor (detect and early exit with 0 result?). Thank you @dhaval24 and @littleaj

**Comment by dan-crough-bmi** [comment]
@littleaj See proposed per @dhaval24 feedback: https://github.com/Microsoft/ApplicationInsights-Java/compare/master...dan-crough-bmi:bugfix/dfc-osbean-noclassdef

Looking at ObjectName,getInstance() javadoc it should never throw either exception, because it only throws if parameter is null (it's set to a constant) or invalid (it's set to java.lang constant), and neither of those can happen. If somehow osMxBeanName ends up null, it just means that getProcessCpuTime() will throw, and that is caught in getProcessCpuUsage() already -- but again, should never happen.

**Comment by littleaj** [comment]
@dhaval24 , @dan-crough-bmi 
I reviewed the code again and dug into the `getPlatformMBeanServer()` implementation a bit; that method is a simple lazy-instantiation factory method. I don't think calling the factory method will have a negative impact on performance. I did, however, make a variable for the OS bean `ObjectName` reference; the constructor for it is quite large and it is constructed each time.

**Comment by dhaval24** [comment]
@littleaj if there is a related issue with respect to this PR please also close that.

**Comment by littleaj** [comment]
@dhaval24 It looks like when they are linked, the bug gets closed automatically.

**Comment by dhaval24** [comment]
@littleaj great then its awesome!! Was just checking.
