### PR TITLE
Fix logging configuration

### LINKED ISSUE #1415: Instrumentation logging level ignored
### Expected behavior
When set the following in applicationinsights.json, I expect to turn off auto log collection (JUL in my case):
```
{
  "instrumentation": {
    "logging": {
      "level": "OFF"
    }
  }
}
```

### Actual behavior
I am still seeing log traces appear in azure monitor

### To Reproduce
Set config as described above and check if trace logs are being sent

### PR DESCRIPTION
**Pull request by trask**
The code was using `level` in one place and `threshold` in another.

`level` is correct (and what's in documentation).

This PR also improves the tests so that the would have caught this issue.

Resolves #1415

### CODE REVIEW

File: agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java [hunk 1]
```diff
@@ -243,12 +243,12 @@ private static String getLoggingFrameworksThreshold(Configuration config, String
         if (logging == null) {
             return defaultValue;
         }
-        Object thresholdObj = logging.get("threshold");
+        Object thresholdObj = logging.get("level");
```
Comment (heyams) [inline agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java:246]: levelObj?

**Review by heyams — APPROVED** [review]
