### PR TITLE
 Adding quotes around security level write method to fix serialization

### LINKED ISSUE #436: TraceTelemetry w/Severity set is no longer appearing in Insights
I picked up Version 1.0.10 yesterday.  After doing so, all my trace lines with severities set stopped writing to application insights.

ie:
```
TraceTelemetry traceTelemetry = new TraceTelemetry("hello", SeverityLevel.Information);
 OperationContext operation = traceTelemetry.getContext().getOperation();
 operation.setId("MyTransactionId");
 telemetry.trackTrace(traceTelemetry);
```

The above stopped tracing with 1.0.10

while if I do the same thing, but set the SeverityLevel to null, it works:
```
TraceTelemetry traceTelemetry = new TraceTelemetry("hello", null);
 OperationContext operation = traceTelemetry.getContext().getOperation();
 operation.setId("MyTransactionId");
 telemetry.trackTrace(traceTelemetry);
```

I rolled back to 1.0.9 because of this defect.

### PR DESCRIPTION
**Pull request by dhaval24**
Fix #436 

This was a sanitization issue. Adding quotes around write(String name, com.microsoft.applicationinsights.internal.schemav2.SeverityLevel value) method fixed it.

### CODE REVIEW

**Comment by dhaval24** [comment]
@littleaj as discussed please add a test case which you have already created around the issue in this branch. Thanks.

File: core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java [hunk 1]
```diff
@@ -95,7 +95,9 @@ public void write(String name, int value) throws IOException {
     public void write(String name, com.microsoft.applicationinsights.internal.schemav2.SeverityLevel value) throws IOException {
         if (value != null) {
             writeName(name);
+            out.write(JSON_COMMA);
```
Comment (Dmitry-Matveev) [inline core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java]: Do you need a changelog item for this?

Comment (dhaval24) [reply core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java]: @Dmitry-Matveev Yes we would need changelog. They are public methods so I think so yes.

**Comment by littleaj** [comment]
@Dmitry-Matveev @dhaval24 I added a test for this scenario.

File: core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java (hunk 1 above)
Comment (littleaj) [reply core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java]: @Dmitry-Matveev @dhaval24 added changelog

**Comment by dhaval24** [comment]
@littleaj This looks good to me.

File: core/src/test/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializerTest.java [hunk 2]
```diff
@@ -275,18 +282,27 @@ public void test() throws IOException {
...
         stubClass.getM1().put("key2", 6);
         stubClass.getM1().put("key3", 7);
+        stubClass.setSeverity(SeverityLevel.Critical);
         StringWriter stringWriter = new StringWriter();
         JsonTelemetryDataSerializer tested = new JsonTelemetryDataSerializer(stringWriter);
         stubClass.serialize(tested);
         tested.close();
         String str = stringWriter.toString();
-        StubClass bac = new Gson().fromJson(str, StubClass.class);
+        System.out.println("serailized=\n"+str);
```
Comment (dhaval24) [inline core/src/test/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializerTest.java]: Do we need this print statement here? I believe it will output on console which everyone (other devs) would not be aware of without looking at the code.

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,5 +1,8 @@
 # CHANGELOG
 
+## Version 1.0.11
```
Comment (dhaval24) [inline CHANGELOG.md]: @littleaj as we changed the public facing method do we need to provide description of what has been changed in the implementation of the method? Rest looks fine.

File: core/src/test/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializerTest.java (hunk 2 above)
Comment (littleaj) [reply core/src/test/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializerTest.java]: Gradle suppresses sysout by default, but I can take this out.

File: CHANGELOG.md (hunk 3 above)
Comment (littleaj) [reply CHANGELOG.md]: I can modify this to reflect that this fixes a regression in trackTrace/trackException
