### PR TITLE
Fix appender tests

### LINKED ISSUE #569: Logging UnitTests failing intermittantly
Occasionally, I'll see the unit tests fail with one or two test failures in the `/logging/*` space.

Here's an example of one of such failures:
```
2018-02-22T21:07:17.1653665Z com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests > testLoggerMessageIsRetainedWhenReportingException STANDARD_ERROR
2018-02-22T21:07:17.1654670Z     AI: INFO 22-02-2018 21:07, 10(Test worker): Configuration file has been successfully found as resource
2018-02-22T21:07:19.3888085Z 
2018-02-22T21:07:19.3889202Z com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests > testLoggerMessageIsRetainedWhenReportingException FAILED
2018-02-22T21:07:19.3889986Z     java.lang.AssertionError: expected:<1> but was:<2>
2018-02-22T21:07:19.3890754Z         at org.junit.Assert.fail(Assert.java:88)
2018-02-22T21:07:19.3891250Z         at org.junit.Assert.failNotEquals(Assert.java:834)
2018-02-22T21:07:19.3891790Z         at org.junit.Assert.assertEquals(Assert.java:645)
2018-02-22T21:07:19.3892306Z         at org.junit.Assert.assertEquals(Assert.java:631)
2018-02-22T21:07:19.3893328Z         at com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests.testLoggerMessageIsRetainedWhenReportingException(ApplicationInsightsAppenderTests.java:71)
```

This assertion is checking how many telemetry items were received by the mocked channel. Locally, I've only seen failures with something along the lines of `java.lang.AssertionError: expected:<1> but was:<`**`0`**`>`, so I thought it was a timing issue.

To test this hypothesis I added a 1 s. sleep before the assertion. Here was the result:
```
com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests > testLoggerMessageIsRetainedWhenReportingException FAILED
    java.lang.AssertionError: expected:<1> but was:<55>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests.testLoggerMessageIsRetainedWhenReportingException(ApplicationInsightsAppenderTests.java:76)

com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests > testAppenderSendsGivenEvent FAILED
    java.lang.AssertionError: expected:<1> but was:<40>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppenderTests.testAppenderSendsGivenEvent(ApplicationInsightsAppenderTests.java:67)
```
Very interesting.

I don't think this is something wrong with the code, but the test setup. I'm adding a JUnit `@Rule` to dump the collected telemetry when there's a failure. Hopefully that will reveal the root cause.

### PR DESCRIPTION
**Pull request by littleaj**
Fix #569.

Suppressed logging for HttpClient in QuickPulse code.

### CODE REVIEW

File: logging/log4j1_2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppenderTests.java [hunk 1]
```diff
@@ -42,8 +50,31 @@
     @Before
     public void setup() {
         setMockTelemetryChannelToAIAppender();
+        Assert.assertTrue("MockTelemetryChannel not clear....", LogChannelMockVerifier.INSTANCE.getTelemetryCollection().isEmpty());
     }
 
+    @Rule
+    public TestWatcher watcher = new TestWatcher() {
```
Comment (littleaj) [inline logging/log4j1_2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppenderTests.java]: If the test fails, this prints all the traces received.

File: logging/log4j1_2/appenderSrc/test/resources/log4j.xml [hunk 2]
```diff
@@ -26,11 +26,23 @@
     <appender name="test" class="com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender">
         <param name="instrumentationKey" value="c9341531-05ac-4d8c-972e-36e97601d5ff" />
         <layout class="org.apache.log4j.PatternLayout">
-            <param name="ConversionPattern" value="%-5p %c{1} - %m%n"/>
+            <param name="ConversionPattern" value="%-5p %c - %m%n"/>
         </layout>
     </appender>
+    <appender name="console" class="org.apache.log4j.ConsoleAppender">
```
Comment (littleaj) [inline logging/log4j1_2/appenderSrc/test/resources/log4j.xml]: Added this for better debugging. I was able to figure out which logger to turn off after enabling this appender.

File: logging/log4j1_2/appenderSrc/test/resources/log4j.xml [hunk 3]
```diff
@@ -26,11 +26,23 @@
...
+        <layout class="org.apache.log4j.PatternLayout">
+            <param name="ConversionPattern" value="%-5p %c - %m%n"/>
+        </layout>
+    </appender>
+
+    <!-- suppresses repackaged HttpClient logger -->
+    <logger name="com.microsoft.applicationinsights.core.dependencies.http">
```
Comment (littleaj) [inline logging/log4j1_2/appenderSrc/test/resources/log4j.xml]: This was the problem.

File: logging/logging.gradle [hunk 4]
```diff
@@ -56,6 +56,7 @@ sourceSets {
     }
 }
 
+findbugs.sourceSets = [sourceSets.main]
```
Comment (littleaj) [inline logging/logging.gradle]: findbugs "found a bug" in the tests. It doesn't like that the watcher is public and never used. Since that's not how it works and I don't want to spend time making a filter file for the tests right now, we'll only run findbugs on shipping code.

File: logging/log4j1_2/appenderSrc/test/resources/log4j.xml [hunk 5]
```diff
@@ -26,11 +26,23 @@
     <appender name="test" class="com.microsoft.applicationinsights.log4j.v1_2.ApplicationInsightsAppender">
         <param name="instrumentationKey" value="c9341531-05ac-4d8c-972e-36e97601d5ff" />
```
Comment (dhaval24) [inline logging/log4j1_2/appenderSrc/test/resources/log4j.xml]: @littleaj is this real iKey? If yes please remove it asap!

File: logging/log4j1_2/appenderSrc/test/resources/log4j.xml (hunk 3 above)
Comment (dhaval24) [reply logging/log4j1_2/appenderSrc/test/resources/log4j.xml]: Nice catch! I like this.

File: logging/logging.gradle (hunk 4 above)
Comment (dhaval24) [reply logging/logging.gradle]: Makes sense!

File: logging/log4j1_2/appenderSrc/test/resources/log4j.xml (hunk 5 above)
Comment (littleaj) [reply logging/log4j1_2/appenderSrc/test/resources/log4j.xml]: It's not, but I'm going to change it to make it more "mocked".
