### PR TITLE
Byte code instrumentation fix

### LINKED ISSUE #428: Agent cannot capture oracle dependency calls to Insert statements
Agent currently cannot capture Oracle Insert statements through statement.exectueUpdate() method. Needs more validation on other methods also.

### PR DESCRIPTION
**Pull request by dhaval24**
Fix #428, #418, #286, #277, #276 , #365 

This pull request fixes the java.lang.Verify error which was being caused in JDK version 1.7 onwards because of improper instrumentation. Changes here facilitate the creation of StackMap frame (a datastructure introduced in JDK 1.7 and mandated in 1.8), fixes constructor instrumentation issue along with improper constructor signature for SQLServer.

#276 mentions issues with HTTPCLIENT 42, however on current testing things work fine for HTTPCLIENT 43 and since its more secure it is advisable to upgrade to this client.

This pull request also upgrades the ASM version to ASM 5.2 

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [x] Changes in public surface reviewed
- [x] CHANGELOG.md updated

### CODE REVIEW

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java [hunk 1]
```diff
@@ -153,6 +153,8 @@ public static String getAgentJarLocation() throws UnsupportedEncodingException {
         }
 
         String path = AgentImplementation.class.getProtectionDomain().getCodeSource().getLocation().getPath();
+        int index = path.lastIndexOf('/');
```
Comment (Dmitry-Matveev) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java]: Is it always in this notation across the platforms or sometimes can be '\\'?

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+        }
+
+        if ((class1.isInterface()) || (class2.isInterface())) {
+            return "java/lang/Object";
+        }
+
+        do {
+            class1 = class1.getSuperclass();
+        }
+        while (!(class1.isAssignableFrom(class2)));
```
Comment (Dmitry-Matveev) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java]: Any possible issue with endless cycle or exception here if class1 has no more superClass and class2 happens to be not assignable (e.g. null or something...)?

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java [hunk 3]
```diff
@@ -243,7 +251,8 @@ private ClassVisitorFactory classFactoryForSqlServer() {
             @Override
             public ClassVisitor create(ClassInstrumentationData classInstrumentationData, ClassWriter classWriter) {
                 HashSet<String> ctorSignatures = new HashSet<String>();
-                ctorSignatures.add("(Lcom/microsoft/sqlserver/jdbc/SQLServerConnection;Ljava/lang/String;II)V");
+                ctorSignatures.add("(Lcom/microsoft/sqlserver/jdbc/SQLServerConnection;Ljava/lang/String;" +
+                        "IILcom/microsoft/sqlserver/jdbc/SQLServerStatementColumnEncryptionSetting;)V");
```
Comment (Dmitry-Matveev) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java]: Is it the same parameter across all SQL calls we'd need to monitor or specific to some version? The previous signature looked more generic.

File: agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultByteCodeTransformerTest.java [hunk 4]
```diff
@@ -26,11 +26,11 @@
...
 
 public final class DefaultByteCodeTransformerTest {
-    @Test
-    public void noClassInstrumentationDataTest() {
-        DefaultByteCodeTransformer tested = new DefaultByteCodeTransformer(null, false);
-        byte[] mockArray = new byte[1];
-        byte[] result = tested.transform(mockArray, "mock");
-        assertSame(result, mockArray);
-    }
+//    @Test
```
Comment (Dmitry-Matveev) [inline agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultByteCodeTransformerTest.java]: Should we delete the test if no longer relevant or uncomment and fix if it still is?

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java (hunk 1 above)
Comment (dhaval24) [reply agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java]: @Dmitry-Matveev It's a good question. I have an idea for 2 platforms I have tested so far. Java 8 has by default class loader of URLClassLoader type so it won't hit this part of the class .Java 9 has default classloader called "app" which is not of the type URLClassLoader and hence hits this part and only works for this change. I am not sure about other JVM's though.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java (hunk 2 above)
Comment (dhaval24) [reply agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java]: @Dmitry-Matveev to be specific about this, this is the exact implementation as how ASM does by default. Only reason to override this method was because ASM uses Class.getClassLoader() method to load the current class and therefore it gets the ClassLoader which doesn't have all the required classes loaded in it. In this override I pass the ClassLoader from the Callee in order to avoid the lookup and have the classloader which has all the required classes loaded. Therefore I believe that since there is minimal change done from ASM implementation this possibility is very narrow. Is there a way we can test this? How can we know if there is a null being passed or something like that?

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java (hunk 3 above)
Comment (dhaval24) [reply agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java]: So the default signature of the constructor for JDBC driver version 6.2 is the one I changed. With the previous signature we were missing the constructor instrumentation. Now with the older drivers it might well be possible that signature was one mentioned before but nonetheless I believe enterprise can upgrade to latest JDBC drivers.

**Comment by dhaval24** [comment]
@Dmitry-Matveev  I have fixed the test for DefaultByteCodeTransformerTest and commented the tests which do not have any asserts. They just add to build time as they are not verifying anything for now.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java [hunk 5]
```diff
@@ -153,6 +153,8 @@ public static String getAgentJarLocation() throws UnsupportedEncodingException {
         }
 
         String path = AgentImplementation.class.getProtectionDomain().getCodeSource().getLocation().getPath();
```
Comment (SergeyKanzhelev) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java]: Use https://docs.oracle.com/javase/8/docs/api/java/nio/file/Paths.html instead of string?

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java [hunk 6]
```diff
@@ -153,6 +153,8 @@ public static String getAgentJarLocation() throws UnsupportedEncodingException {
...
+        int index = path.lastIndexOf('/');
+        path = path.substring(0, index + 1);
```
Comment (SergeyKanzhelev) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java]: check that index is not `-1`. Just in case so code will not throw. Also see above - using Path instead of string will help

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java [hunk 7]
```diff
@@ -0,0 +1,48 @@
+package com.microsoft.applicationinsights.agent.internal.agent;
+
+
+import org.objectweb.asm.ClassWriter;
+
+public class CustomClassWriter extends ClassWriter {
```
Comment (SergeyKanzhelev) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java]: Please add comment. And make sure you need it to be `public`

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+
+    ClassLoader classLoader;
+
+    public CustomClassWriter(int writerFlag, ClassLoader loader)
+    {
+        super(writerFlag);
+        this.classLoader = loader;
+    }
+
+    protected String getCommonSuperClass(String className1, String className2)
```
Comment (SergeyKanzhelev) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java]: Add comment for this method.

File: agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java [hunk 9]
```diff
@@ -28,10 +28,10 @@
 
 public final class ClassInstrumentationDataTest {
     private final static String MOCK_CLASS_NAME = "ClassName";
-    private final static String MOCK_METHOD = "Method";
-    private final static String MOCK_SIGNATURE_1 = "Signature1";
-    private final static String MOCK_SIGNATURE_2 = "Signature2";
-    private final static String MOCK_SIGNATURE_3 = "Signature3";
+//    private final static String MOCK_METHOD = "Method";
```
Comment (SergeyKanzhelev) [inline agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java]: remove instead of commenting. BTW, why commenting?

File: gradle/common-java.gradle [hunk 10]
```diff
@@ -40,8 +40,8 @@ if (java6JreDir) {
         bootClasspath += "$archivePath;"
     }
     tasks.withType(JavaCompile) {
-        sourceCompatibility = 1.6
-        targetCompatibility = 1.6
+        sourceCompatibility = 1.8
```
Comment (SergeyKanzhelev) [inline gradle/common-java.gradle]: So you dropped 1.7 support?

File: core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java [hunk 11]
```diff
@@ -1,514 +1,520 @@
...
-                    explain.close();
-                } catch (SQLException e) {
-                }
-            }
-        }
-
-        return explainSB;
-    }
-}
+/*
```
Comment (SergeyKanzhelev) [inline core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java]: what changed in this file?

File: gradle/common-java.gradle (hunk 10 above)
Comment (dhaval24) [reply gradle/common-java.gradle]: I made it so because sometimes in some situations it the 1.7 target code would not produce the desired exceptions because these changes were mandated from JDK 1.8. Also, we need to decide till what point do we need to support backward compatibility in the SDK. We might not be able to use all the new features of JDK 8 like automatic inference of types in <> operator, passing of functions using lambda expressions etc which is modern java.

Comment (dhaval24) [reply gradle/common-java.gradle]: If required no harm in reverting it back if things work fine. However at one point we need to make this decision.

File: agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java (hunk 9 above)
Comment (dhaval24) [reply agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java]: Commenting because this signature was used in tests which were relying on getDecisionMethod() however it turns out that there is no such method in ClassInstrumentationData class.

Comment (dhaval24) [reply agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java]: May be if there is an idea to get this tests running in future, that was the reason.

File: core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java (hunk 11 above)
Comment (dhaval24) [reply core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java]: @grlima to comment more on this. At-least my intuition here was that while sending telemetry for SqlServer there are only two arguments that come in the methoddata object whereas previously there was a strict condition which checked arguments should be more than or equal to 3

**Comment by dhaval24** [comment]
@SergeyKanzhelev I have addressed most of the concerns including using the Paths class for locating the agent jar, adding comments and also making CustomClassWriter package private instead of public.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java [hunk 12]
```diff
@@ -136,24 +139,36 @@ private static void appendJarsToBootstrapClassLoader(Instrumentation inst) throw
...
             InternalAgentLogger.INSTANCE.logAlways(InternalAgentLogger.LoggingLevel.ERROR, "Error while trying to fetch Jar Location, Exception: " + throwable.getMessage());
         }
 
-        String path = AgentImplementation.class.getProtectionDomain().getCodeSource().getLocation().getPath();
-        return URLDecoder.decode(path, "UTF-8");
+        String stringPath = AgentImplementation.class.getProtectionDomain().getCodeSource().getLocation().getPath();
+        if (stringPath.charAt(0) == '/') {
+            stringPath = stringPath.substring(1);
+        }
+        Path path = Paths.get(stringPath);
```
Comment (littleaj) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java]: The `java.nio.*` classes were introduced in 1.7. It's my understanding we still want compatibility with 1.6. If that's still the case, this needs to be reworked. @grlima, can you confirm?

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java (hunk 2 above)
Comment (littleaj) [reply agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriter.java]: @dhaval24 To test this method, you could refactor it into a `public static` utility method which takes the ClassLoader along with the other parameters and write tests against that.

File: agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java (hunk 9 above)
Comment (littleaj) [reply agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java]: What happens if you uncomment these tests?

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java (hunk 3 above)
Comment (littleaj) [reply agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java]: @dhaval24 Does this limit the supported driver versions?

**Comment by dhaval24** [comment]
@SergeyKanzhelev @littleaj @Dmitry-Matveev @grlima I have pushed changes in this PR which are now addressing all the possible bytecode concerns we have seen till the date. As far as unit tests are concerned I still do not have a way to perform tests and our agent code does not have ones till the date, however this is a blocking issue and we need to get it fixed. I have done end to end testing in several test application and changes work fine.  The CustomClass Loader now performs the commonSuperClass lookup without actually loading the class. The PR also introduces changes in the Application-Insights web gradle file to include shadow jar plugin hence eliminating class path hell issues and also introduces a public constructor in the WebRequestTracking filter to address SpringBoot solutions as discussed.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java [hunk 13]
```diff
@@ -136,24 +135,28 @@ private static void appendJarsToBootstrapClassLoader(Instrumentation inst) throw
...
+                        InternalAgentLogger.INSTANCE.logAlways(InternalAgentLogger.LoggingLevel.INFO,"Agent jar found at " + urlPath);
                         int index = urlPath.lastIndexOf('/');
                         urlPath = urlPath.substring(0, index + 1);
                         return urlPath;
                     }
+
                 }
             }
         } catch (Throwable throwable) {
+            InternalAgentLogger.INSTANCE.logAlways(InternalAgentLogger.LoggingLevel.ERROR,"Unable to find the Agent Jar");
```
Comment (littleaj) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java]: Remove this extra log message. It's going to the same logger, same level and there's no new information here. Feel free to update the wording in the log message on the next line.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriterv2.java [hunk 14]
```diff
@@ -0,0 +1,138 @@
...
+
+    /**
+     * This method returns common super class for both the classes without actually loading
+     * the class using forName(). If no super class is present it returns java/lang/Object class.
+     * @param type1
+     * @param type2
+     * @return The String for the common super class of both the classes
+     */
+    @Override
+    protected String getCommonSuperClass(final String type1, final String type2) {
```
Comment (littleaj) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriterv2.java]: At the very least this method should have a unit test, if not the whole class.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriterv2.java [hunk 15]
```diff
@@ -0,0 +1,138 @@
...
+
+import java.io.IOException;
+import java.io.InputStream;
+
+/**
+ * This class overwrites default class writer of ASM to use the ClassLoader
+ * provided by DefaultByteCode transformer (This loader essentially has all
+ * the required classes already loaded)
+ */
+public class CustomClassWriterv2 extends org.objectweb.asm.ClassWriter {
```
Comment (littleaj) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriterv2.java]: I'm not a fan of _SomeClass**V2**_ naming schemes. If the modifications can't be described in one or two words, the go with "branding" it; e.g. _AppInsightsCustomClassWriter_.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultClassVisitor.java [hunk 16]
```diff
@@ -51,7 +52,7 @@ public void visit(int version, int access, String name, String signature, String
     @Override
     public MethodVisitor visitMethod(int access, String name, String desc, String signature, String[] exceptions) {
         MethodVisitor originalMV = super.visitMethod(access, name, desc, signature, exceptions);
-
+        originalMV = new JSRInlinerAdapter(originalMV, access, name, desc, signature, exceptions);
```
Comment (littleaj) [inline agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultClassVisitor.java]: The next line checks for `null`, which will now always be false. Either that part of the condition is no longer valid and should be removed, or it should be relocated.

File: agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java (hunk 9 above)
Comment (littleaj) [reply agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java]: Please address these tests. If they are failing, they should be updated to reflect the new functionality. If they are no longer valid, they should be removed (and explain why this is the case).

File: gradle/common-java.gradle [hunk 17]
```diff
@@ -40,8 +40,8 @@ if (java6JreDir) {
         bootClasspath += "$archivePath;"
     }
     tasks.withType(JavaCompile) {
-        sourceCompatibility = 1.6
```
[the remark this answers is not in the document]
Comment (littleaj) [reply gradle/common-java.gradle]: this.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultClassVisitor.java (hunk 16 above)
Comment (dhaval24) [reply agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultClassVisitor.java]: well yes I think can be moved one step above may be.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriterv2.java (hunk 14 above)
Comment (dhaval24) [reply agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriterv2.java]: Sure I will get couple of them.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriterv2.java (hunk 15 above)
Comment (dhaval24) [reply agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CustomClassWriterv2.java]: I think this can be just refactored as CustomClassWriter I will do that.

File: agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java (hunk 13 above)
Comment (dhaval24) [reply agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java]: okay thanks will do this.

File: agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultByteCodeTransformerTest.java [hunk 18]
```diff
@@ -27,10 +27,10 @@
 
 public final class DefaultByteCodeTransformerTest {
     @Test
-    public void noClassInstrumentationDataTest() {
+    public void noClassInstrumentationDataTest() throws ClassNotFoundException {
```
[the remark this answers is not in the document]
Comment (dhaval24) [reply agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultByteCodeTransformerTest.java]: sure this is by mistake. I think there is any need of throws too.

File: agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java (hunk 9 above)
Comment (dhaval24) [reply agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java]: @littleaj all the asserts within this tests are commented because there is a method which they intended to write is missing. Therefore there is no use to create unnecessary objects during test run time. It will add overhead only.

File: core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java (hunk 11 above)
Comment (dhaval24) [reply core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java]: @littleaj this file was edited by @grlima when prepared statements for sqlserver where not working (i.e not capturing the query data) we can no revert this changes back because we no longer need to loose if condition in the sendSQLTelemetry() method.

**Comment by dhaval24** [comment]
@littleaj I have addressed your concerns in the previous review except the diff in CoreAgentNotification Handler. In my IDE git diff shows no difference so will have to figure it out. @grlima had pushed those changes so if you can have a look @grlima would be great.

File: core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java (hunk 11 above)
Comment (littleaj) [reply core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java]: you can see the difference here: `git diff master -- CoreAgentNotificationsHandler.java > CoreAgentNotificationsHandler.java.diff` (assuming PWD is the file's location). It's the line endings. Your IDE should be set to preserve the existing line ending characters. There may be a way to fix this in IntelliJ, but you may have to load it in Notepad++ an do a find/replace.

If you want to just checkout a clean copy and make the changes again, add use this command to see the "actual" changes: `git diff master -w -- CoreAgentNotificationsHandler.java > CoreAgentNotificationsHandler.java.diff` to ignore all whitespace changes

File: agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java (hunk 9 above)
Comment (littleaj) [reply agent/src/test/java/com/microsoft/applicationinsights/agent/internal/agent/ClassInstrumentationDataTest.java]: @dhaval24 as discussed, let's just revert this to the master copy and we'll come back to it later. Then, we'll figure out if it needs to be removed or modified so it works.

**Comment by dhaval24** [comment]
Thanks Sergey for your comment. @littleaj and @grlima I am waiting for your approval to merge this into master. Please have a look.

**Comment by dhaval24** [comment]
Folks I have updated the last missing piece on my end which was updating changelog file. If there is anything else which is left let me know so we that we can then merge this.
