### PR TITLE
Fix Spring Boot 4 Micrometer auto-configuration and add actuator metrics smoke coverage

### LINKED ISSUE #4577: Micrometer metrics not pushed to Application Insights after upgrade to Spring Boot 4.0.0
### Summary
After upgrading my service to Spring Boot 4.0.0, Micrometer metrics are no longer being exported to Azure Application Insights. My investigation suggests the Azure Application Insights Java agent does not yet support Spring Boot 4.0.0.

### Expected behavior
Micrometer metrics (JVM metrics, custom metrics) should be visible in Azure Application Insights / Azure Monitor metrics for Spring Boot service after deployment.

### Actual behavior
After upgrading to Spring Boot 4.0.0, no Micrometer metrics appear in Application Insights for the service, despite the app running normally.

### To Reproduce
Application is started with the Application Insights Java agent loaded using -javaagent:agent.jar parameter.

### System information
Application Insights Java agent 3.7.6
Spring Boot 4.0.0

### Screenshots
Following screenshots has been done when debugging Spring Boot application in IntelliJ with Application Insights Java agent attached.

Beans of **io.micrometer.core.instrument.MeterRegistry** type in the **Spring Boot 3.5.8** application:
Image

Beans of **io.micrometer.core.instrument.MeterRegistry** type after upgrade to **Spring Boot 4.0.0**:
Image

### PR DESCRIPTION
**Pull request by xiang17**
Fix #4577.

Spring Boot 4 moved Micrometer metrics auto-configuration classes from
`org.springframework.boot.actuate.autoconfigure.metrics.*` to
`org.springframework.boot.micrometer.metrics.autoconfigure.*`.

Our Micrometer instrumentation was still keyed only to the Spring Boot 3 class
names, which meant the Azure Monitor meter registry auto-configuration was not
being inserted for Spring Boot 4 applications. As a result, custom Micrometer
metrics such as `demo.requests.total` could be present locally but never reach
Application Insights.

This change updates the Micrometer instrumentation to support both Spring Boot 3
and Spring Boot 4 auto-configuration class names, and adds smoke coverage for
the Spring Boot 4 path.

## Docs for reference

Old package summary, Spring Boot 3.5.8
https://javadoc.io/static/org.springframework.boot/spring-boot-actuator-autoconfigure/3.5.8/org/springframework/boot/actuate/autoconfigure/metrics/package-summary.html
This page explicitly says:
Package org.springframework.boot.actuate.autoconfigure.metrics
Auto-configuration for actuator metrics and Micrometer.

New package summary, Spring Boot 4.0.0
https://javadoc.io/static/org.springframework.boot/spring-boot-micrometer-metrics/4.0.0/org/springframework/boot/micrometer/metrics/autoconfigure/package-summary.html
This page explicitly says:
Package org.springframework.boot.micrometer.metrics.autoconfigure
Auto-configuration for metrics with Micrometer.

## Suggested testing

- `./gradlew :smoke-tests:apps:ActuatorMetricsSpringBoot4:smokeTest --tests '*ActuatorMetricsSpringBoot4Test$Java21Test'`
- `./gradlew :smoke-tests:apps:Micrometer:smokeTest --tests "*MicrometerTest*"`

### CODE REVIEW

File: smoke-tests/apps/ActuatorMetricsSpringBoot4/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/ActuatorMetricsSpringBoot4Test.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+    }
+    for (DataPoint point : data.getMetrics()) {
+      if ("demo_requests_total".equals(point.getName()) && point.getValue() >= 1) {
+        return true;
+      }
+    }
+    return false;
+  }
+
+  @Environment(JAVA_17)
```
Comment (xiang17) [inline smoke-tests/apps/ActuatorMetricsSpringBoot4/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/ActuatorMetricsSpringBoot4Test.java:61]: Spring Boot 4.0 requires Java 17 or later. https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-4.0-Migration-Guide

File: smoke-tests/apps/ActuatorMetricsSpringBoot4/src/main/java/com/microsoft/applicationinsights/smoketestapp/SpringBootApp.java [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+public class SpringBootApp {
+
+  @Bean
+  public ServletWebServerFactory servletWebServerFactory() {
+    return new TomcatServletWebServerFactory();
+  }
+
+  @Bean
+  public MeterRegistry meterRegistry() {
+    return Metrics.globalRegistry;
```
Comment (trask) [inline smoke-tests/apps/ActuatorMetricsSpringBoot4/src/main/java/com/microsoft/applicationinsights/smoketestapp/SpringBootApp.java:24]: I think returning Metrics.globalRegistry here bypasses the new Spring Boot 4 actuator auto-configuration path. MetricsInstrumentation already adds AzureMonitorMeterRegistry to the global registry, so this smoke test can stay green even if the PR's Boot 4 import hook never runs.

Comment (trask) [reply smoke-tests/apps/ActuatorMetricsSpringBoot4/src/main/java/com/microsoft/applicationinsights/smoketestapp/SpringBootApp.java:24]: you could try reverting your fix and re-running this smoke test to make sure it fails without your fix

**Comment by landsman** [comment]
do you have time to finalize this please?

**Comment by xiang17** [comment]
I fixed the smoke test so that in the first commit above ([Update smoke test so that it misses the metrics when reverting the fix](https://github.com/microsoft/ApplicationInsights-Java/pull/4672/commits/25be67be0528bc89015b036815b1fa7a33dfb818)), the smoke test would fail because the code doesn't have the fix.

Then after reapplying the fix in the next commit ([Revert "revert fix"](https://github.com/microsoft/ApplicationInsights-Java/pull/4672/commits/ea12d345d3a0dafb4b1663517ad91577eb3593d2)) and the smoke test should pass, thus proving the smoke test can validate the fix.

**Review by trask — APPROVED** [review]

**Review by rajkumar-rangaraj — APPROVED** [review]
